export const SUCCESS = 'SUCCESS';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
export const PAGE_NOT_FOUND = 'PAGE_NOT_FOUND';
